name: Testing SSH Access
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Connect via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: "172.20.71.180"
          username: "keicee"
          key: ${{ secrets.SSH_KEY }}
          timeout: 600s
          debug: true
          script: touch ~/github-file.txt
